config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :clients do
      collection do
        get 'login', to: 'clients#login', as: 'login'
        get 'session', to: 'clients#create_user_session', as: 'get_session'
        post 'session', to: 'clients#create_user_session', as: 'session'
      end
    end

    resources :doctors

    resources :appointments do
      collection do
        get 'download', to: 'appointments#download', as: 'download'
      end
    end

    root "doctors#index"
  end
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :appointments, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validate :email_format, :supported_currency

  private

  def email_format
    errors.add(:email, I18n.t('error_message_email')) unless Constants::EMAIL_REGEXP.match(email)
  end

  def supported_currency
    errors.add(:currency_preference, I18n.t('models.errors.unsupported_currency')) unless Constants::ACCEPTED_CURRENCIES.include?(currency_preference)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user, only: :show
  include Constants

  # GET /clients/new
  def new
    render :new, locals: { appointment_id: params[:appointment_id], rates: params[:rates] }
  end

  # GET /clients/1
  def show
  end

  # POST /clients or /clients.json
  def create
    client_helper = ClientPartialHelper.new(client_params, params)

    respond_to do |format|
      if client_helper.process_appointment
        cookies.permanent[:email] = client_params[:email]
        format.turbo_stream { render turbo_stream: turbo_stream.replace('client-form', partial: 'appointments/success', locals: { appointment: client_helper.appointment }) }
        format.html { redirect_to Appointment.find(params[:appointment_id]) }
      else
        format.turbo_stream do
          flash.now[:notice] = true
          render turbo_stream: turbo_stream.replace('client-form', partial: 'clients/form', locals: { appointment_id: params[:appointment_id], rates: $fixer_client.standard_prices })
        end
        format.html { render :new, locals: { appointment_id: params[:appointment_id], rates: $fixer_client.standard_prices }, status: :unprocessable_entity }
      end
    end
  end

  def create_user_session
    client = Client.find_by(email: params[:email])
    if client
      cookies.permanent[:email] = params[:email]
      redirect_to client
    else
      flash.now[:notice] = t('clients.login.missing_client')
      render(action: :login, status: :unprocessable_entity)
    end

    
  end

  private
  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:email, :currency_preference)
  end

  def authenticate_user
    @client = Client.find(params[:id])
    redirect_to login_clients_path unless @client.email == cookies[:email]
  end
end

app/views/clients/_form.html.erb
<div id="client-form" class="px-3" data-controller="client-form"> 
  <div class="d-none d-lg-block py-5 my-4"></div>

  <div class="col col-lg-6 row gx-2 mx-auto mt-5 mb-3 my-lg-5">
    <div class="col my-auto fw-bolder fs-4 text-center">
      <%= t('.title') %>
    </div>
  </div>

  <% if flash.notice %>
      <div class="row">
        <div class="col col-lg-5 mx-auto px-4 text-danger">
          <%= t('error_message') %>
        </div>
      </div>
  <% end %>

  <%= form_with(model: Client, html: { novalidate: true, "data-client-form-target": "form" ,"data-action": "submit->client-form#validateForm:prevent" }) do |form| %>
    <%= hidden_field_tag :appointment_id, appointment_id %>
    <div class="row">
      <div class="col col-lg-5 row gx-2 mx-auto mt-2">
        <%= form.label :email, style: "display: block", class: "form-label fw-bold" %>
        <%= form.email_field :email, value: cookies[:email] || nil, class: "form-control py-4 border border-2 rounded-3", placeholder: t('email_entry'), "data-client-form-target": "emailField", "data-action": "keypress->client-form#validateEmailWhileTyping" %>
      </div>
    </div>
    <div class="row">
      <div class="col col-lg-5 mx-auto p-2 text-danger d-none" data-client-form-target="emailError">
        <%= t('error_message_email') %>
      </div>
    </div>

    <div class="row g-0 mx-auto mt-5 mb-3">
      <div class="col col-lg-5 mx-auto fw-bold ms-n2 ms-lg-auto">
        <%= t('.currency_selector') %>
      </div>
    </div>

    <div class="row">
      <div class="col col-lg-5 row mx-auto g-0">
        <% Constants::ACCEPTED_CURRENCIES.each do |currency| %>
          <div class="col-4 g-3" data-client-form-target="currencyButton">
            <%= form.radio_button :currency_preference , currency, { class: "btn-check", rate: "#{rates[currency]}", checked: currency == "INR" } %>
            <%= form.label :currency_preference, currency, value: currency , class: "btn btn-outline-primary w-100", "data-action": "click->client-form#updatePaymentButton" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row mt-5 my-lg-4 px-2 px-lg-0 pt-3 pt-lg-0">
      <div class="col col-lg-5 mx-auto mt-4 g-0">
        <%= form.submit t('.default_payment', amount:Constants::PRICE ), class:"btn btn-primary w-100 py-3 py-lg-4 fs-7 fw-bolder", "data-client-form-target": "paymentButton" %>
        <div class="btn btn-primary w-100 py-2 d-none">
          <div class="spinner-border text-light"></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/clients/login.html.erb
<div id="client-login-form">
    <div class="d-none d-lg-block py-5 my-4"></div>

    <div class="row my-5">
        <div class="col text-center fw-bolder fs-4">
            <%= t('email_entry') %>
        </div>
    </div>

    <%= form_tag(session_clients_path) do %>
        <div class="row">
            <div class="col col-lg-5 mx-auto">
                <%= email_field_tag :email, nil , class: "form-control py-3 border border-2 fs-6" %>
            </div>
        </div>

        <% if flash.notice %>
            <div class="row">
                <div class="col col-lg-5 mx-auto px-4 text-danger">
                    <%= flash.notice %>
                </div>
            </div>
        <% end %>

        <div class="row my-5">
            <div class="col col-lg-5 mx-auto">
                <%= submit_tag "Submit", class:"btn btn-primary w-100 py-4 payment" %>
            </div>
        </div>
    <% end %>
</div>

app/views/clients/new.html.erb
<%= render "clients/form", appointment_id: appointment_id, rates: rates %>

app/views/clients/show.html.erb
<div id="appointments-list">
    <div class="row my-4">
        <div class="col-auto d-lg-none">
            <%= image_tag('arrow-left.svg') %>
        </div>
        <div class="col text-center d-none d-lg-block fs-4 fw-bolder">
            <%= t('my_appointments') %>
        </div>
        <div class="col-auto text-center d-lg-none fs-5">
            <%= t('my_appointments') %>
        </div>
    </div>

    <div class="row col-12 mx-auto justify-content-center gap-5">
        <% @client.appointments.each do | app | %>
            <div class="col-12 col-lg-5 bg-white shadow-sm rounded px-3 py-5 my-3">
                <div class="row g-0 pt-3">
                    <div class="col-auto me-3">
                        <%= image_tag(app.doctor.avatar, size: "77x77", style: "border-radius: 4px; background-color: lightgray;") if app.doctor.avatar.attached? %>
                    </div>
                    <div class="col-auto">
                        <div class="row g-0 fw-bolder mb-2"><%= app.doctor.name %></div>
                        <div class="row g-0"><%= app.doctor.location %></div>
                    </div>
                </div>

                <div class="row g-0 my-4">
                    <div class="col fs-7 grey-font">
                        <%= t('.consultation_details') %>
                    </div>
                </div>

                <div class="row g-0">
                    <div class="col-auto me-1">
                        <%= image_tag('calendar-white.svg',size: "16") %>
                    </div>
                    <div class="col-auto fw-bold py-1">
                        <% text = app.date.to_date.date_in_words %>
                        <%= "#{text[:specifier]} #{text[:date]} #{text[:month_long]}" %>
                    </div>
                    <div class="col-auto mx-auto text-center text-black-50 py-1">
                        |
                    </div>
                    <div class="col-auto me-1">
                        <%= image_tag('time-square.svg', size: "16") %>
                    </div>
                    <div class="col-auto fw-bold py-1">
                        <%= app.time_string %>
                    </div>
                </div>

                <div class="row g-0 mt-5 mb-4 pt-3">
                    <div class="col">
                        <%= t('.download_invoice') %>
                    </div>
                </div>

                <div class="row g-0 mb-5 gx-3">
                    <% Constants::DOWNLOAD_FORMATS.each do |format| %>
                        <div class="col-auto">
                            <%= link_to "#{format.upcase}", download_appointments_path(request.params.merge(format: format, id: app.id)), class: "btn btn-dark py-1 px-4 fw-light fs-7" %>
                        </div>
                    <% end %>
                </div>

                <div class="row g-0 mt-5 mb-4 pt-3">
                    <div class="col row bg-amt-paid p-3 rounded g-0">
                        <div class="col-auto me-auto fw-light">
                            <%= t('.amount_paid') %>
                        </div>
                        <div class="col-auto text-primary fw-bolder">
                        <%= "#{'%.2f' % [app.amount_in_original_currency]} #{app.currency}" %>
                        </div>
                    </div>
                </div>

                <div class="row g-0">
                    <div class="col">
                        <%= button_to t('.cancel'), app, method: :delete, class: "btn btn-primary w-100", disabled: app.cancel? ? false : true %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>