config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :clients do
      collection do
        get 'login', to: 'clients#login', as: 'login'
        get 'session', to: 'clients#create_user_session', as: 'get_session'
        post 'session', to: 'clients#create_user_session', as: 'session'
      end
    end

    resources :doctors

    resources :appointments do
      collection do
        get 'download', to: 'appointments#download', as: 'download'
      end
    end

    root "doctors#index"
  end
end

app/models/doctor.rb
require 'date'

class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_one_attached :avatar

  validates :name, :location, :working_hours, presence: true
  validate :working_hours_format

  def available_slots(date)
    work_slots = working_hours.split(',')
    work_slots.select! { |slot| slot > Time.now.strftime('%k') } if date.today?
    work_slots - booked_slots(date)
  end

  def available_slots_for_range
    dates = (Date.today...Date.today + Constants::SCHEDULING_RANGE).map { |date| available_slots(date) }
    (DateRadioButton.today...DateRadioButton.today + Constants::SCHEDULING_RANGE).zip(dates).to_h.reject { |_date, slot| slot.empty? if slot }
  end

  def next_available
    available_slots(Date.today).first
  end

  private

  def booked_slots(date)
    appointments.where(date: date.strftime('%d/%m/%Y')).map(&:time)
  end

  def working_hours_format
    errors.add(:working_hours, I18n.t('models.errors.invalid_hours')) unless Constants::WORKING_HOURS_REGEXP.match(working_hours)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  helper DoctorsHelper

  def index
    @doctors = Doctor.all
    @next_available = @doctors.map(&:next_available)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
  def format_time(time)
    time ? "#{time}:00".to_time.strftime('%l:%M %p') : "N/A"
  end
end

app/views/doctors/index.html.erb
<div class="row">
  <div class="col col-lg-11 mx-auto px-5">
    <div class="row g-0 mt-5 my-lg-4 mx-n4 mx-lg-n2">
      <div class="col-auto lh-sm d-none d-lg-block">
        <%= image_tag('stethoscope.svg') %>
      </div>
      <div class="col-auto lh-sm d-lg-none">
        <%= image_tag('stethoscope.svg', size: "21x21") %>
      </div>
      <div class="col-auto my-auto fs-lg-10 fw-semibold mx-3">
        <%= t('.title') %>
      </div>
    </div>

    <div class="row gy-4 gx-5 mx-n5 px-3 mt-2" id="doctors">
      <% @doctors.each_with_index do |doctor, index| %>
        <div class="col-12 col-lg-6 py-0 py-lg-2 px-1 px-lg-4">
          <div class="container-auto p-3 bg-white border border-black rounded">
            <div class="row g-0">
              <div class="col-auto me-4">
                <%= image_tag(doctor.avatar, size: "77x77", style: "border-radius: 4px; background-color: lightgray;") if doctor.avatar.attached? %>
              </div>
              <div class="col-auto py-2 gy-2">
                <div class="row g-0 fw-bolder"><%= doctor.name %></div>
                <div class="row g-0 mt-2 fs-7 grey-font"><%= doctor.location %></div>
              </div>
            </div>

            <div class="row g-0 mt-2">
              <div class="col-auto row py-3 g-1 fs-8">
                <div class="col-auto fw-bold lime-green-font"> <%= t('.next_available') %></div>
                <div class="col-auto grey-font"> - </div>
                <div class="col-auto grey-font"><%= "#{format_time(@next_available[index])}" %></div>
              </div>
              <div class="col-auto ms-auto">
                <%= link_to t('.book_visit'),new_appointment_path(doctor_id: doctor.id) ,class: 'btn btn-primary btn-block py-3 px-5 fs-7 fw-bolder' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>