config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :clients do
      collection do
        get 'login', to: 'clients#login', as: 'login'
        get 'session', to: 'clients#create_user_session', as: 'get_session'
        post 'session', to: 'clients#create_user_session', as: 'session'
      end
    end

    resources :doctors

    resources :appointments do
      collection do
        get 'download', to: 'appointments#download', as: 'download'
      end
    end

    root "doctors#index"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= t('.app_name')  %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <div class="container-fluid bg-header">
      <div class="row py-2 d-block d-lg-none">
      </div>
      
      <div class="row p-3 px-lg-0">
        <div class="col-5 col-lg-auto offset-lg-1 me-auto me-lg-0 fs-10 fw-bold">
          <%= link_to t('.app_name'), doctors_path, class:"link-dark link-underline-none ps-lg-3" %>
        </div>
        <div class="col-lg-auto d-none d-lg-block">
          <%= image_tag('line.svg') %>
        </div>
        <div class="col-6 col-lg-auto row gx-2">
          <div class="col-auto mx-1">
            <%= image_tag('calendar.svg') %>
          </div>
          <div class="col-auto my-auto fs-7">
            <%= link_to t('my_appointments'), @current_user ? @current_user : login_clients_path, class:"link-dark link-underline-none" %>
          </div>
        </div>
      </div>
    </div>

    <div class="py-3 d-none d-lg-block">
    </div>

    <div class="container-lg mx-auto main-content-container px-3">
      <%= yield %>
    </div>
  </body>
</html>